Butabiika_system/Butabiika_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from Butabiika_system import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^doctors/', include('doctors.urls', namespace='doctors')),
    url(r'^patients/', include('patients.urls', namespace='patients')),

    url(r'^admin/', admin.site.urls),
]

Butabiika_system/patients/urls.py
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.PatientsListView.as_view(), name='patients_list'),
    url(r"patients/(?P<pk>\d+)/$", views.PatientCreateView.as_view(), name='patients_details'),
    url(r"patients/(?P<pk>\d+)/update/$", views.PatientUpdateView.as_view(), name='patients_update'),
    url(r"patients/(?P<pk>\d+)/delete/$", views.PatientDeleteView.as_view(), name='delete_patients'),
    url(r"patients/create/$", views.PatientCreateView.as_view(), name='create_patients'),
]

Butabiika_system/patients/models.py
from django.db import models
from doctors.models import Doctor

# Create your models here.
class Patient(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True)
    location = models.CharField(max_length=100, blank=True)
    description = models.TextField(max_length=1000, blank=True)
    assigned_doctor = models.ForeignKey(Doctor)
    telephone_number = models.CharField(max_length=20, blank=False)

    def __str__(self):
        return self.name


class CreatePatient(models.Model):
    model = Patient
    fields = ['name', 'email', 'location','description','assigned_doctor', 'telephone_number']


class DeletePatient(models.Model):
    model = Patient


class UpdatePatient(models.Model):
    model = Patient
    fields = ['name', 'email', 'location','description','assigned_doctor', 'telephone_number']

# class Prediction(models.Model):

Butabiika_system/patients/forms.py
from __future__ import unicode_literals
from django.db import models
from django import forms
#from datatables import DataTable
#from django.views.generic import DeleteView


class Patient(forms.Form):
    name = forms.CharField(max_length=200)
    email = forms.EmailField()
    location = forms.CharField(max_length=100)
    description = forms.TextField(max_length=1000, blank=True)
    assigned_doctor = forms.ForeignKey(Doctor)
    telephone_number = forms.IntegerField()

Butabiika_system/Butabiika_system/views.py
from django.shortcuts import render

def home(request):
    return render(request,'home.html')

Butabiika_system/patients/views.py
# Create your views here.
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, DeleteView, CreateView
from django.views.generic.list import ListView
from .models import Patient


class PatientsListView(ListView):
    model = Patient
    template_name = 'patients/patients_list.html'



class PatientCreateView(CreateView):
    model = Patient
    fields = ['name', 'email', 'location','description','assigned_doctor', 'telephone_number']
    success_url = reverse_lazy('patients:patients_list')
    template_name = 'patients/create_patients.html'


class PatientDeleteView(DeleteView):
    model = Patient
    template_name = 'patients/delete_patients.html'
    success_url = reverse_lazy('patients:patients_list')



class PatientUpdateView(UpdateView):
    model = Patient
    fields = ['name', 'email', 'location','description','assigned_doctor', 'telephone_number']
    # template_name_suffix = '_update_form'
    template_name = 'patients/patients_update.html'

    success_url = reverse_lazy('patients:patients_list')


class PatientDetailView(DetailView):
    model = Patient
    success_url = reverse_lazy('patients:patients_list')
    template_name = 'patients/patients_details.html'

def patients_menu(request):
    patients = Patient.objects.all()
    return render(request, 'patients/patients_menu.html', {
        'patients': patients,
    })

Butabiika_system/patients/templates/patients/create_patients.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Add Patients{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}
    <h3>Add New Patients</h3>
    <!--align="center"-->
    <form method="post"  >
        {% csrf_token %}
        {% bootstrap_form form %}


        <input type="submit" value="Add Patients." class="btn btn-primary">

        <a href="{% url 'patients:patients_list' %}"class="btn btn-primary"> Cancel</a>
    </form>
{% else %}
{% endif %}
{% endblock %}

Butabiika_system/patients/templates/patients/delete_patients.html
{% extends 'base.html' %}
{% block title %}{{object_name}} Confirm delete?{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
            <p>You're about to delete Patients{{ object }}. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}

                <input class="btn btn-success" type="submit" value="Confirm"/>
                        <a href="{% url 'patients:patients_list' %}"class="btn btn-primary"> Cancel</a>

            </form>
        </div>
    </div>
{% endblock %}

Butabiika_system/patients/templates/patients/patients_details.html
{% extends 'base.html' %}


{% block title %}Patients {% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        </div>
        <div class="container">

            <div class="row">
                <p>Patients Name: {{ object.name }}</p>
                <p>Patients Email Address: {{ object.email }}</p>
                <p>Patients Phone Number: {{ object.phone_number }}</p>
                <p>Patients Location: {{ object.location }}</p>
            </div>
        </div>

{% endblock %}

Butabiika_system/patients/templates/patients/patients_list.html
{% extends 'base.html' %}
{% block title %}patients {% endblock %}

{% block content %}
    <div class="page-header" align="center" xmlns="http://www.w3.org/1999/html">
        <p class="lead">Available patients</p>
    </div>
    <div class="container">

        <div class="row">
            <div>
                <div class="panel panel-primary">
                    <div class="panel-body">
                    <div class="pull-right">
                                <a href="{% url 'patients:create_patients' %}" align="pull-right"
                                   class="btn btn-primary"
                                   role="button"><span
                                        class="glyphicon glyphicon-plus"></span>
                                    Add Patients</a>
                            </div>
                        <div class="container" align="center">

                            <!-- Large modal -->

                            <table class="table table-responsive" id="dev-table">
                                <thead>
                                <tr>


                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email Address</th>
                                    <th>Location</th>
                                    <th>description</th>
                                    <th>Assigned Doctor</th>
                                    <th>telephone Number</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for patient in object_list %}
                                    <tr>
                                        <td>
                                            {{ patient.id|capfirst }}
                                        </td>
                                         <td>
                                            {{ patient.name|capfirst }}
                                        </td>
                                        <td>
                                            {{ patient.email|capfirst }}
                                        </td>
                                        <td>
                                            {{patient.location|capfirst }}
                                        </td>
                                          <td>
                                            {{ patient.description|capfirst }}
                                        </td>
                                          <td>
                                            {{ patient.assigned_doctor|capfirst }}
                                        </td>
                                        <td>
                                            {{ patient.telephone_number }}
                                        </td>
                                        <td class="text-center">
                                        <td class="text-center">
                                            <a class='btn btn-info btn-xs'
                                               href="{% url 'patients:patients_update' patient.pk %}"><span
                                                    class="glyphicon glyphicon-edit"></span>
                                                Edit
                                            </a>
                                            <a href="{% url 'patients:delete_patients' patient.pk %}" class="btn btn-danger btn-xs"><span
                                                    class="glyphicon glyphicon-remove"></span>
                                                Delete
                                            </a>
                                            <a href="{% url 'patients:patients_details' patient.pk %}"
                                               class="btn btn-success btn-xs"><span
                                                    class="glyphicon glyphicon-eye-open"></span>
                                                Details
                                            </a>
                                        </td>


                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

Butabiika_system/patients/templates/patients/patients_update.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}Confirm Update?{% endblock %}

{% block content %}
    <div id="content-container" class="container p-none">
        <div class="side-p">
            <h3>Are you sure?</h3>
             <p>You're about to edit Patients object. Please confirm.</p>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" value="Update Patients " class="btn btn-success">
                <a class="btn btn-link" href="{% url 'patients:patients_list' %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

Butabiika_system/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

1. Predictive analytics increase the accuracy of diagnoses.

Physicians can use predictive algorithms to help them make more accurate diagnoses. For example, when patients come to the ER with chest pain, it is often difficult to know whether the patient should be hospitalized. If the doctors were able to answers questions about the patient and his condition  into a system with a tested and accurate predictive algorithm that would assess the likelihood that the patient could be sent home safely, then their own clinical judgments would be aided. The prediction would not replace their judgments but rather would assist.

In a visit to one's primary care physician, the following might occur: The doctor has been following the patient for many years. The patient's genome includes a gene marker for early onset Alzheimer's disease, determined by researchers using predictive analytics. This gene is rare and runs in the patient's  family on one side. Several years ago, when it was first discovered, the patient agreed to have his blood taken to see if he had the gene. He did. There was no gene treatment available, but evidence based research indicated to the PCP conditions that may be helpful for many early Alzheimer's patients.

Ever since, the physician has had the patient engaging in exercise, good nutrition, and brain games apps that the patient downloaded on his smart phone and which automatically upload to the patient's portal. Memory tests are given on a regular basis and are entered into the electronic medical record  (EMR), which also links to the patient portal. The patient himself adds data weekly onto his patient portal to keep track of time and kinds of exercises, what he is eating, how he has slept, and any other variable that his doctor wishes to keep track of.

Because the PCP has a number of Alzheimer's patients, the PCP has initiated an ongoing predictive study with the hope of developing a predictive model for individual likelihood of memory maintenance and uses, with permission, the data thus entered through the patients' portals. At this visit, the physician  shares the good news that a gene therapy been discovered for the patient's specific gene and recommends that the patient receive such therapy.